language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode
  - ree
  - ruby-head

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head

notifications:
  email:
    - sfgeorge-toadhopper-turtle.testudo12@wronghead.com
  irc:
    channels: "irc.freenode.org#toadhopper"