language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ree
  - ruby-head
  - jruby-head

before_install:
 - sudo apt-get update
 - sudo apt-get install libxml2

notifications:
  email:
    - sfgeorge-toadhopper-turtle.testudo12@wronghead.com
  irc:
    channels: "irc.freenode.org#toadhopper"